import {ColorType} from "../Enums/Colors";
import {PieceType} from "../Enums/PieceType";

export const initialPositions: Array<{pieceType: PieceType, color: ColorType, x: string, y: number}> = [
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'A', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'B', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'C', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'D', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'E', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'F', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'G', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.White, x: 'H', y: 2},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'A', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'B', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'C', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'D', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'E', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'F', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'G', y: 7},
    {pieceType: PieceType.Pawn, color: ColorType.Black, x: 'H', y: 7},
    {pieceType: PieceType.Rook, color: ColorType.White, x: 'A', y: 1},
    {pieceType: PieceType.Rook, color: ColorType.White, x: 'H', y: 1},
    {pieceType: PieceType.Rook, color: ColorType.Black, x: 'A', y: 8},
    {pieceType: PieceType.Rook, color: ColorType.Black, x: 'H', y: 8},
    {pieceType: PieceType.Queen, color: ColorType.White, x: 'D', y: 1},
    {pieceType: PieceType.Queen, color: ColorType.Black, x: 'D', y: 8},
    {pieceType: PieceType.King, color: ColorType.White, x: 'E', y: 1},
    {pieceType: PieceType.King, color: ColorType.Black, x: 'E', y: 8},
    {pieceType: PieceType.Knight, color: ColorType.White, x: 'B', y: 1},
    {pieceType: PieceType.Knight, color: ColorType.White, x: 'G', y: 1},
    {pieceType: PieceType.Knight, color: ColorType.Black, x: 'B', y: 8},
    {pieceType: PieceType.Knight, color: ColorType.Black, x: 'G', y: 8},
    {pieceType: PieceType.Bishop, color: ColorType.White, x: 'F', y: 1},
    {pieceType: PieceType.Bishop, color: ColorType.White, x: 'C', y: 1},
    {pieceType: PieceType.Bishop, color: ColorType.Black, x: 'F', y: 8},
    {pieceType: PieceType.Bishop, color: ColorType.Black, x: 'C', y: 8}
];